matcha/main/routes.py
from flask import Blueprint, render_template, abort, session, request, flash, redirect, url_for
from jinja2 import TemplateNotFound
from matcha.db import db_connect, dict_factory
from matcha.utils.general import getdist
from matcha.utils.decorators import not_logged_in, is_logged_in, is_admin

from matcha.main.search import get_currentUser, get_SuggestedUsers, get_wantedsexuality, search_users

main = Blueprint('main', __name__,
				template_folder='./templates', static_folder='static')



@main.route('/')
@not_logged_in
def home():
	try:
		return render_template('home.html')
	except TemplateNotFound:
		abort(404)

@main.route('/admin')
@is_admin
def admin():
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT * FROM users WHERE id IN (SELECT reportedId FROM reports)")
	reporteds = cur.fetchall()
	con.close()
	try:
		return render_template('admin.html', users=reporteds)
	except TemplateNotFound:
		abort(404)

@main.route('/ban/<reportedId>')
@is_admin
def ban_user(reportedId):
	con = db_connect()
	cur = con.cursor()
	cur.execute("DELETE FROM reports WHERE reportedId=?", [reportedId])
	cur.execute("DELETE FROM users WHERE id=?", [reportedId])
	con.commit()
	con.close()
	try:
		flash('User has been banned!', 'success')
		return redirect(url_for('main.admin'))
	except TemplateNotFound:
		abort(404)

@main.route('/remove/<reportedId>')
@is_admin
def remove_report(reportedId):
	con = db_connect()
	cur = con.cursor()
	cur.execute("DELETE FROM reports WHERE reportedId=?", [reportedId])
	con.commit()
	con.close()
	try:
		flash('Report has been removed!', 'success')
		return redirect(url_for('main.admin'))
	except TemplateNotFound:
		abort(404)


@main.route('/feed', methods=['GET', 'POST'])
@is_logged_in
def feed():
	#Get current user
	user = get_currentUser(session['id'])
	if user['complete'] == 1:
		if (request.method == 'POST'):
			# Do The actual Search
			users = search_users(request.form, user['gender'], user['sexuality'])
		else:
			# Get suggested users
			users = get_SuggestedUsers(user['sexuality'], user['gender'])
	else:
		flash("Please complete your profile to view the feed!", "danger")
		return render_template('feed.html', setup="Profile is not complete",form=request.form)
	
	try:
		return render_template('feed.html', users=users, form=request.form)
	except TemplateNotFound:
		abort(404)

matcha/main/templates/admin.html
{% extends 'layout.html' %} {% block content %}

<table class="table table-striped table-hover">
	<thead class="thead-dark">
		<tr >
			<th scope="col">Reported</th scope="col">
			<th scope="col">Ban</th>
			<th scope="col">Remove</th>
		</tr>
	</thead>
	<tbody>
		{% for user in users %}
		<tr >
			<td>
				<a href="{{ url_for('users.profile', username=user.username) }}"
					>{{ user.username }}</a
				>
			</td>
			<td>
				<a
					href="{{ url_for('main.ban_user', reportedId=user.id) }}"
					class="text-danger"
					>Ban</a
				>
			</td>
			<td>
				<a
					href="{{ url_for('main.remove_report', reportedId=user.id) }}"
					class="text-danger"
					>Remove</a
				>
			</td>
		</tr>
		{% endfor %}
	</tbody>
</table>

{% endblock %}

matcha/main/templates/feed.html
{% extends 'layout.html' %} {% block content %} {% if users %}
<h2>Feed</h2>
{% endif %}
<div class="row justify-content-around">
	{% if users %} {% for user in users %}
	<div class="card col-md-5 feed">
		{% if user.path %}
		<img
			style="height: 250px; width: 100%; display: block;"
			src="{{ url_for('static', filename='photos/' + user.path) }}"
			alt="Card image"
		/>
		{% else %}
		<img
			style="height: 250px; width: 100%; display: block;"
			src="{{ url_for('static', filename='photos/' + 'default.jpeg') }}"
			alt="Card image"
		/>
		{% endif %}
		<div class="card-body">
			<h4 class="card-title">
				<a href="{{ url_for('users.profile', username=user.username) }}"
					>{{ user.username }}
				</a>
			</h4>
			<h6 class="card-subtitle mb-2 text-muted">
				{% if user.age %} {{ user.age }} {% else %} Not Specified
				{%endif %}
			</h6>
			<!-- shhh this is the distance -->
			<h6 class="card-subtitle mb-2 text-muted">
				{% if user.distance %} {{ user.distance }} km {% else %} Unknown
				{%endif %}
			</h6>
		</div>
	</div>
	{% endfor %} {% endif %}
</div>
{% endblock %} {% block sidebar %}
<div class="content-section">
	<form action="" id="query" method="POST">
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Search</legend>
			<div class="form-group">
				<label for="search" class="form-control-label">Search</label>
				{% if form.search %}
				<input
					type="text"
					name="search"
					id="search"
					class="form-control form-control-md"
					value="{{ form.search }}"
				/>
				{% else %}
				<input
					type="text"
					name="search"
					id="search"
					class="form-control form-control-md"
				/>
				{% endif %}
			</div>
			<div class="form-group">
				<label for="Order">Order By</label>
				<select name="Order" id="Order">
					{% if form.Order == "Fame" %}
					<option selected="selected">Fame</option>
					{% else %}
					<option>Fame</option>
					{% endif %} {% if form.Order == "Distance" %}
					<option selected="selected">Distance</option>
					{% else %}
					<option>Distance</option>
					{% endif %} {% if form.Order == "Age" %}
					<option selected="selected">Age</option>
					{% else %}
					<option>Age</option>
					{% endif %} {% if form.Order == "Username" %}
					<option selected="selected">Username</option>
					{% else %}
					<option>Username</option>
					{% endif %}
				</select>
			</div>
			<div class="form-row align-items-center">
				<div class="age-div">
					<label class="age-label">Min Age</label>
					{% if form.MinAge %}
					<input
						type="number"
						name="MinAge"
						id="MinAge"
						min="10"
						value="{{ form.MinAge }}"
					/>
					{% else %}
					<input type="number" name="MinAge" id="MinAge" min="10" />
					{% endif %}
				</div>
				<div class="age-div">
					<label class="age-label">Max Age</label>
					{% if form.MaxAge %}
					<input
						type="number"
						name="MaxAge"
						id="MaxAge"
						max="100"
						value="{{ form.MaxAge }}"
					/>
					{% else %}
					<input type="number" name="MaxAge" id="MaxAge" max="100" />
					{% endif %}
				</div>
			</div>
			<div class="form-row align-items-center">
				<div class="age-div">
					<label class="age-label">Min Fame</label>
					{% if form.MinFame %}
					<input
						type="number"
						name="MinFame"
						id="MinFame"
						min="0"
						step="0.1"
						value="{{ form.MinFame }}"
					/>
					{% else %}
					<input
						type="number"
						name="MinFame"
						id="MinFame"
						min="0"
						step="0.1"
					/>
					{% endif %}
				</div>
				<div class="age-div">
					<label class="age-label">Max Fame</label>
					{% if form.MaxFame %}
					<input
						type="number"
						name="MaxFame"
						id="MaxFame"
						max="5"
						step="0.1"
						value="{{ form.MaxFame }}"
					/>
					{% else %}
					<input
						type="number"
						name="MaxFame"
						id="MaxFame"
						max="5"
						step="0.1"
					/>
					{% endif %}
				</div>
			</div>
			<div class="form-row align-items-center">
				<div class="age-div">
					<label class="age-label">Min Distance</label>
					{% if form.MinDist %}
					<input
						type="number"
						name="MinDist"
						id="MinDist"
						min="0"
						step="0.1"
						value="{{ form.MinDist }}"
					/>
					{% else %}
					<input
						type="number"
						name="MinDist"
						id="MinDist"
						min="0"
						step="0.1"
					/>
					{% endif %}
				</div>
				<div class="age-div">
					<label class="age-label">Max Distance</label>
					{% if form.MaxDist %}
					<input
						type="number"
						name="MaxDist"
						id="MaxDist"
						step="0.1"
						value="{{ form.MaxDist }}"
					/>
					{% else %}
					<input
						type="number"
						name="MaxDist"
						id="MaxDist"
						step="0.1"
					/>
					{% endif %}
				</div>
				<div class="form-group">
					<label for="city" class="form-control-label">city</label>
					{% if form.city %}
					<input
						type="text"
						name="city"
						id="city"
						class="form-control form-control-md"
						value="{{ form.city }}"
					/>
					{% else %}
					<input
						type="text"
						name="city"
						id="city"
						class="form-control form-control-md"
					/>
					{% endif %}
				</div>
			</div>
			<div class="form-check">
				{% if form.tags %}
				<input
					type="checkbox"
					name="tags"
					id="tags"
					class="form-check-input"
					checked="True"
				/>
				{% else %}
				<input
					type="checkbox"
					name="tags"
					id="tags"
					class="form-check-input"
				/>
				{% endif %}
				<label for="tags" class="form-check-label">Same tags</label>
			</div>
		</fieldset>
		<div id="SubmitForm" class="form-group d-flex justify-content-between">
			{% if not session.page %}
			<button
				type="submit"
				class="btn btn-outline-primary"
				name="submit"
				value="Search"
			>
				Search
			</button>
			{% else %}
			<button
				type="submit"
				class="btn btn-outline-primary"
				name="submit"
				value="Previous"
			>
				Previous
			</button>
			<label>
				{{ session.page }}
			</label>
			<button
				type="submit"
				class="btn btn-outline-primary"
				name="submit"
				value="Next"
			>
				Next
			</button>
			{% endif %}
		</div>
	</form>
</div>
<script>
	function change() {
		document.getElementById("SubmitForm").innerHTML =
			"<button type='submit' class='btn btn-outline-primary' name='submit' value='Search'>Search</button>";
	}

	var inputs = document.getElementsByTagName("input");
	for (i = 0; i < inputs.length; i++) {
		// inputs[i].onchange = change;
		inputs[i].onfocusout = change;
	}

	var select = document.getElementById("Order");
	select.onchange = change;
</script>
{% endblock %}

matcha/main/templates/home.html
{% extends "layout.html" %} {% block content %}

<!-- <h1>Matcha</h1>
<h3>Find your perfect match now!</h3>
<div>
	<a href="{{ url_for('auth.login') }}" class="btn btn-primary">Login</a>
	<a href="{{ url_for('auth.register') }}" class="btn btn-success"
		>Register</a
	>
</div> -->
<div class="col-md-12 col-lg-7">
	<h3 style="text-transform: uppercase;">
		Welcome to Matcha
	</h3>
	<p class="mb-5">
		Your perfect match could be a click away!
	</p>
	<p>
		<a href="{{ url_for('auth.login') }}" class="btn btn-outline-primary"
			>Login</a
		>
		<a href="{{ url_for('auth.register') }}" class="btn btn-outline-success"
			>Register</a
		>
	</p>
</div>

{% endblock content %}