matcha/chat/routes.py
from flask import Blueprint, render_template, session, flash, redirect, url_for, abort
from matcha.utils.decorators import not_logged_in, is_logged_in
from .. import socketio
from flask_socketio import join_room, leave_room, emit
from matcha.db import db_connect, dict_factory
from datetime import datetime
import json

chat = Blueprint('chat', __name__,
				 template_folder='./templates')

# Messaging
@chat.route('/')
@is_logged_in
def sessions():
	try:
		return render_template('chat.html', Matches=getMatches(), title="Chat")
	except:
		abort(500)


def escape(s, quote=True):
	s = s.replace("&", "&amp;") # Must be done first!
	s = s.replace("<", "&lt;")
	s = s.replace(">", "&gt;")
	if quote:
		s = s.replace('"', "&quot;")
		s = s.replace('\'', "&#x27;")
	return s

def getmessagecount(id, system = False):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	SQL = "SELECT COUNT(id) as count FROM messages WHERE receiveId=? AND seen = 0 "
	if (not system):
		SQL += "AND senderId <> 1"
	else:
		SQL += "AND senderId = 1"
	cur.execute(SQL, [id])
	result = cur.fetchone()
	con.close()
	return result['count']

def getsystemmessages(id):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT message FROM messages WHERE senderId = 1 AND receiveId = ?", [id])
	result = cur.fetchall()
	con.close()
	return result

def getMatches():
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	if session.get('id') is not None:
		id = session['id']
		cur.execute("""SELECT users.username, matches.id, users.id as userid FROM matches LEFT OUTER JOIN users on (matches.user1 = users.id) Where matches.user2 = ? AND NOT UPPER(username)='SYSTEM'
		UNION
		SELECT users.username, matches.id, users.id as userid FROM matches LEFT OUTER JOIN users on (matches.user2 = users.id) Where matches.user1 = ? AND NOT UPPER(username)='SYSTEM'""", [id, id])
		result = cur.fetchall()
		for res in result:
			cur.execute("SELECT * FROM messages WHERE matchId=? AND receiveId=? AND seen=?", [res['id'], session['id'], 0])
			tot = cur.fetchall()
			res['amount'] = len(tot)
		con.close()
	else:
		return None
	return result

def getMessages(room):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT * FROM messages WHERE matchId=?", [room])
	result = cur.fetchall()
	con.close()
	return result

def getReciever(room, id):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("""SELECT users.username, matches.id, users.id as userid FROM matches LEFT OUTER JOIN users on (matches.user1 = users.id) Where matches.id = ? AND matches.user2 = ?
		UNION
		SELECT users.username, matches.id, users.id as userid FROM matches LEFT OUTER JOIN users on (matches.user2 = users.id) Where matches.id = ? AND matches.user1 = ?""", [room, id, room, id])
	result = cur.fetchone()
	con.close()
	return result

def notinmatch(room):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT count(id) FROM matches where (user1 = ? or user2 = ?) AND id = ?", [session['id'], session['id'], room])
	result = cur.fetchone()
	return (result == 1)

def getusernamebyid(id):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT * FROM users WHERE id = ? ", [id])
	result = cur.fetchone()
	con.close()
	return result

def getroombyuserids(id1, id2):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT id FROM matches WHERE user1 = ? AND user2 = ?", [id1, id2])
	result = cur.fetchone()
	con.close()
	return result

def insertMessage(arr):
	con = db_connect()
	cur = con.cursor()
	cur.execute("INSERT INTO messages (matchId, senderId, receiveId, message, time) VALUES (?,?,?,?,?)", arr)
	con.commit()
	con.close()

def setseen(id, room):
	con = db_connect()
	cur = con.cursor()
	cur.execute(
	"""UPDATE messages SET seen = 1
		WHERE matchId = ? 
		AND receiveId = ?""",
		[room, id])
	con.commit()
	con.close()

@socketio.on('getHistory')
def getHistory(data):
	session['room'] = str(data['room'])
	#set messages as seen
	setseen(session['id'], data['room'])
	if (notinmatch(session['room'])):
		abort(403)
	#construct messages
	reciever = getReciever(session['room'], session['id'])['username']
	messages = getMessages(data['room'])
	strmessages = ''
	for message in messages:
		if (message['senderId'] == session['id']):
			css = "send"
			user = session['username']
		else:
			css = "recieve"
			user = reciever
		if (message['seen'] == 1):
			status = 'seen'
		else:
			status = 'unseen'
		strmessages += """
		<div class="message content-section {}">
			<h5>@{}</h5>
			<p>{}</p>
			<span class="time-right {} ">{}</span>
		</div>
		<br>""".format(css, user, message['message'], status, message['time'])
	emit('load', strmessages)

@socketio.on('connect')
def connect_all():
	if (not session.get('room')):
		session['room'] = 'System'
	Matches=getMatches()
	if Matches is not None:
		for match in Matches:
			join_room(str(match['id']))

@socketio.on('send')
def message(data):
	if (session.get('room')):
		date_time = datetime.now().strftime("%m/%d/%Y, %H:%M:%S")
		receiveId = getReciever(session['room'], session['id'])['userid']
		msg = escape(data['message'])
		if not msg.isspace():
			insertMessage([session['room'], session['id'], receiveId, msg, date_time])
			message = """
			<div class="message content-section send">
				<h5>@{}</h5>
				<p>{}</p>
				<span class="time-right">{}</span>
			</div>
			<br>""".format(session['username'], msg,date_time)
			try:
				JSON = {"message": message, "rawmsg": msg, "roomname": session['room'], "sender": session['username']}
				emit('update', JSON, room=session['room'], json=True)
			except Exception as ex:
				print('JSON ERROR' + ex)

@is_logged_in
def sysmsg(data):
	date_time = datetime.now().strftime("%m/%d/%Y, %H:%M:%S")
	# username = getusernamebyid(data['id'])
	msg = escape(data['message'])
	room = getroombyuserids(1, data['id'])['id']
	# print(room)
	if not msg.isspace():
		insertMessage([room, 1, data['id'], msg, date_time])
		message = """
		<div class="message content-section">
			<h5>@{}</h5>
			<p>{}</p>
			<span class="time-right">{}</span>
		</div>
		<br>""".format(session['username'], msg,date_time)
		try:
			JSON = {"message": message, "rawmsg": msg, "roomname": str(room), "sender": "System"}
			emit('update', JSON, room=str(room), json=True, namespace = '/')
		except Exception as ex:
				print('JSON ERROR' + ex)

@socketio.on('update_msgcnt')
@is_logged_in
def updatemessagecount():
	session['sysnotif'] = getsystemmessages(session['id'])
	session['sysmsgcnt'] = getmessagecount(session['id'], True)
	session['msgcnt'] = getmessagecount(session['id'])
	return [session['sysnotif'], session['sysmsgcnt'], session['msgcnt']]

@socketio.on('update_system_seen')
@is_logged_in
def update_system_seen():
	con = db_connect()
	cur = con.cursor()
	cur.execute(""" UPDATE messages SET seen = 1 WHERE receiveId = ? AND senderId = 1 """, [session['id']])
	con.commit()
	con.close()
	return 0

matcha/main/routes.py
from flask import Blueprint, render_template, abort, session, request, flash, redirect, url_for
from jinja2 import TemplateNotFound
from matcha.db import db_connect, dict_factory
from matcha.utils.general import getdist
from matcha.utils.decorators import not_logged_in, is_logged_in, is_admin

from matcha.main.search import get_currentUser, get_SuggestedUsers, get_wantedsexuality, search_users

main = Blueprint('main', __name__,
				template_folder='./templates', static_folder='static')



@main.route('/')
@not_logged_in
def home():
	try:
		return render_template('home.html')
	except TemplateNotFound:
		abort(404)

@main.route('/admin')
@is_admin
def admin():
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT * FROM users WHERE id IN (SELECT reportedId FROM reports)")
	reporteds = cur.fetchall()
	con.close()
	try:
		return render_template('admin.html', users=reporteds)
	except TemplateNotFound:
		abort(404)

@main.route('/ban/<reportedId>')
@is_admin
def ban_user(reportedId):
	con = db_connect()
	cur = con.cursor()
	cur.execute("DELETE FROM reports WHERE reportedId=?", [reportedId])
	cur.execute("DELETE FROM users WHERE id=?", [reportedId])
	con.commit()
	con.close()
	try:
		flash('User has been banned!', 'success')
		return redirect(url_for('main.admin'))
	except TemplateNotFound:
		abort(404)

@main.route('/remove/<reportedId>')
@is_admin
def remove_report(reportedId):
	con = db_connect()
	cur = con.cursor()
	cur.execute("DELETE FROM reports WHERE reportedId=?", [reportedId])
	con.commit()
	con.close()
	try:
		flash('Report has been removed!', 'success')
		return redirect(url_for('main.admin'))
	except TemplateNotFound:
		abort(404)


@main.route('/feed', methods=['GET', 'POST'])
@is_logged_in
def feed():
	#Get current user
	user = get_currentUser(session['id'])
	if user['complete'] == 1:
		if (request.method == 'POST'):
			# Do The actual Search
			users = search_users(request.form, user['gender'], user['sexuality'])
		else:
			# Get suggested users
			users = get_SuggestedUsers(user['sexuality'], user['gender'])
	else:
		flash("Please complete your profile to view the feed!", "danger")
		return render_template('feed.html', setup="Profile is not complete",form=request.form)
	
	try:
		return render_template('feed.html', users=users, form=request.form)
	except TemplateNotFound:
		abort(404)

matcha/templates/layout.html
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8" />
		<meta name="viewport" content="width=device-width, initial-scale=1.0" />
		<meta http-equiv="X-UA-Compatible" content="ie=edge" />
		<link rel="shortcut icon" href="{{ url_for('static', filename='favicon.png') }}" type="image/x-icon"/>
		<link rel="stylesheet" href="{{ url_for('static', filename='bootstrap.min.css') }}"/>
		<link rel="stylesheet" href="{{ url_for('static', filename='main.css') }}"/>
		
		<link href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.11.2/css/all.min.css" rel="stylesheet"/>
		<!-- Bootstrap -->
		<script src="https://code.jquery.com/jquery-3.5.1.min.js" integrity="sha256-9/aliU8dGd2tb6OSsuzixeV4y/faTqgFtohetphbbj0=" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/popper.js@1.16.1/dist/umd/popper.min.js" integrity="sha384-9/reFTGAW83EW2RDu2S0VKaIzap3H66lZH81PoYlFhbGU+6BZp6G7niu735Sk7lN" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.min.js" integrity="sha384-w1Q4orYjBQndcko6MimVbzY0tgp4pWB4lZ7lr30WKz0vr/aWKhXdBNmNb5D92v7s" crossorigin="anonymous"></script>
		
		
		<script src="//cdnjs.cloudflare.com/ajax/libs/socket.io/2.2.0/socket.io.js" integrity="sha256-yr4fRk/GU1ehYJPAs8P4JlTgu0Hdsp4ZKrx8bDEDC3I=" crossorigin="anonymous"></script>
		<script src="{{url_for('static', filename='js/socket.js')}}" Content-Type="application/javascript"></script>
		
		{% if title %}
		<title>Matcha - {{ title }}</title>
		{% else %}
		<title>Matcha</title>
		{% endif %}
	</head>
	<body>
		<header class="site-header">
			{% include 'navbar.html' %}
		</header>

		<main role="main" class="container">
			<div class="row">
				<div
					class="{{'col-md-8' if self.sidebar() else 'col-md-8 offset-md-2'}}"
				>
					{% with messages =
					get_flashed_messages(with_categories=true) %} {% if messages
					%} {% for category, message in messages %}
					<div class="alert alert-{{ category}}">
						{{ message }}
					</div>
					{% endfor %} {% endif %} {% endwith %} {% block content %}{%
					endblock %}
				</div>
				{% if self.sidebar() %}
				<div class="col-md-4">
					{% block sidebar %}{% endblock %}
				</div>
				{% endif %}
			</div>
		</main>
	</body>
</html>

matcha/templates/navbar.html
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
	<a class="navbar-brand" href="{{ url_for('main.home') }}">Matcha</a>
	<button
		class="navbar-toggler"
		type="button"
		data-toggle="collapse"
		data-target="#navbarColor01"
		aria-controls="navbarColor01"
		aria-expanded="false"
		aria-label="Toggle navigation"
	>
		<span class="navbar-toggler-icon"></span>
	</button>

	<div class="collapse navbar-collapse" id="navbarColor01">
		<ul class="navbar-nav mr-auto">
			{% if session.logged_in %}
			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('main.feed') }}">Feed</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('chat.sessions') }}"
					>Messages
					<sub id="msgcnt">
						{% if session.msgcnt > 0 %} {{ session.msgcnt }} {%
						endif %}
					</sub>
				</a>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('main.home') }}">Home</a>
			</li>
			{% endif %}
		</ul>
		<ul class="navbar-nav ml-auto">
			{% if session.logged_in %}
			<li class="nav-item">
				<!-- add badge with count to item aswell -->
				<div class="dropdown show nav-link">
					<i class="far fa-bell" href="#" role="button" id="dropdownMenuLink" data-toggle="dropdown" aria-haspopup="true" aria-expanded="false"
					onclick="socket.emit('update_system_seen')">
						<span class="sysmsgcnt" id="sysmsgcnt"></span>
					</i>
					<div class="dropdown-menu" id="sysnotif" aria-labelledby="dropdownMenuLink">
						{% for sysnotif in session.sysnotif %}
							<a class="dropdown-item" href="#">{{ sysnotif.message }}</a>
						{% endfor %}
					</div>
				</div>

			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('users.profile') }}"
					>Profile</a
				>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('auth.logout') }}"
					>Logout</a
				>
			</li>
			{% else %}
			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('auth.login') }}">Login</a>
			</li>
			<li class="nav-item">
				<a class="nav-link" href="{{ url_for('auth.register') }}"
					>Register</a
				>
			</li>
			{% endif %}
		</ul>
		<!-- <form class="form-inline my-2 my-lg-0">
			<input class="form-control mr-sm-2" type="text" placeholder="Search" />
			<button class="btn btn-secondary my-2 my-sm-0" type="submit">
				Search
			</button>
		</form> -->
	</div>
</nav>