matcha/users/routes.py
from flask import Blueprint, render_template, url_for, request, flash, redirect, session, abort
from jinja2 import TemplateNotFound
from datetime import date 

import secrets
import os

#For sys notifications
from matcha.chat.routes import sysmsg

from matcha.utils.general import get_age
from matcha.auth.utils import hash_password
from matcha.utils.decorators import is_logged_in, is_admin_or_logged_in
from matcha.db import db_connect, dict_factory

ALLOWED_EXTENSIONS = {'.png', '.jpg', '.jpeg'}

users = Blueprint('users', __name__,
				  template_folder='./templates', static_folder='../static')

def update_fame_rating(id):
	total = getprofileviews(id)
	con = db_connect()
	cur = con.cursor()
	cur.execute("SELECT * FROM likes WHERE user2=?", [id])
	like = cur.fetchall()
	likes = len(like)
	cur.execute("SELECT * FROM matches WHERE (user2=? OR user1=?) AND NOT (user1=1 OR user2=1)", [id, id])
	match = cur.fetchall()
	matches = len(match)
	if (total > 0):
		fame = (likes + matches) / total * 5
	else:
		fame = 0
	cur.execute("UPDATE users SET fame=? WHERE id=?", [round(fame, 1), id])
	con.commit()
	con.close()
	return round(fame, 1)

def get_id_from_username(username):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT * FROM users WHERE username=?", [username])
	user = cur.fetchone()
	con.close()
	return user['username']

def save_picture(form_picture):
	random_hex = secrets.token_hex(8)
	_, f_ext = os.path.splitext(form_picture.filename)
	if (f_ext in ALLOWED_EXTENSIONS):
		picture_fn = str(session['id']) + "." + random_hex + f_ext
		picture_path = os.path.join('matcha/static/photos', picture_fn)
		form_picture.save(picture_path)
		return picture_fn
	else:
		flash('Unsupported extention type!', 'danger')
		return 'Empty'

def getprofileviews(id):
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT viewee as count FROM views WHERE viewer=? AND NOT viewer=1", [id])
	result = cur.fetchall()
	con.close()
	return len(result)

def addprofileviews(id):
	views = getprofileviews(id) + 1
	con = db_connect()
	cur = con.cursor()
	cur.execute(
	"""UPDATE users SET totalviews = ?
		WHERE id = ?""",
		[views, id])
	con.commit()
	con.close()

@users.route('/profile', defaults={'username': None}, methods=['GET', 'POST'])
@users.route('/profile/<username>', methods=['GET', 'POST'])
@is_admin_or_logged_in
def profile(username):
	if username == None:
		username = session['username']
	username = username.lower()
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	cur.execute("SELECT * FROM users WHERE username=?", [username])
	result = cur.fetchone()
	if result:
		if username != session['username']:
			cur.execute("SELECT * FROM blocked WHERE userId=? AND blockedId=?", [result['id'], session['id']])
			isblocked = cur.fetchone()
			if isblocked:
				abort(404)
			else:
				cur.execute("SELECT * FROM views WHERE viewee=? AND viewer=?", [result['id'], session['id']])
				view = cur.fetchone()
				if not view:
					cur.execute("INSERT INTO views (viewer, viewee) VALUES(?, ?)", [result['id'], session['id']]) #might not be right lol
					con.commit()
		if request.method == 'POST':
			cur.execute("SELECT * FROM photos WHERE userId=?", [result['id']])
			tot = cur.fetchall()
			if len(tot) < 5:
				picture_file = save_picture(request.files['picture'])
				if picture_file != 'Empty':
					cur.execute("SELECT * FROM photos WHERE userId=?", [result['id']])
					pics = cur.fetchall()
					if not pics:
						cur.execute("INSERT INTO photos (userId, path, profile) VALUES (?, ?, 1)", [session['id'], picture_file])
					else:
						cur.execute("INSERT INTO photos (userId, path) VALUES (?, ?)", [session['id'], picture_file])
					con.commit()
		cur.execute("SELECT * FROM photos WHERE userId=? ORDER BY profile DESC", [result['id']])
		pics = cur.fetchall()
		# Fix this please 
		profile = pics[0] if pics != [] else None
		cur.execute("SELECT * FROM tags WHERE id IN (SELECT tagId FROM usertags WHERE userId=?)", [result['id']])
		tags = cur.fetchall()
		cur.execute("""
		SELECT
		u.fname, u.lname, u.email, u.id, u.username, u.gender, u.password, u.bio, u.birthdate, u.sexuality, u.verify,
		COUNT(p.profile) AS profileset
		FROM
			users AS u
		LEFT JOIN photos AS p ON u.id = p.userId
		WHERE u.id=?
		GROUP BY u.id
		""", [session['id']])
		complete = cur.fetchone()
		if complete['fname'] and complete['lname'] and complete['username'] and complete['email'] and complete['gender'] and complete['birthdate'] and complete['sexuality'] and complete['bio'] and complete['profileset'] > 0:
			cur.execute("UPDATE users SET complete=? WHERE id=?", [1, complete['id']])
		else:
			cur.execute("UPDATE users SET complete=? WHERE id=?", [0, complete['id']])
		con.commit()
		blocked = 0
		liked = 0
		matched = 0
		if (username != session['username']):
			cur.execute("SELECT * FROM blocked WHERE userId=? AND blockedId=?", [session['id'], result['id']])
			block = cur.fetchone()
			blocked = 1 if block != None else 0
			cur.execute("SELECT * FROM matches WHERE (user1=? AND user2=?) OR (user1=? AND user2=?)", [session['id'], result['id'], result['id'], session['id']])
			match = cur.fetchone()
			if match:
				matched = 1
			else:
				cur.execute("SELECT * FROM likes WHERE user1=? AND user2=?", [session['id'], result['id']])
				like = cur.fetchone()
				liked = 1 if like != None else 0
		con.close()
		#update profile views
		# referrer = request.referrer
		if (username != session['username']):
			data = {'id': result['id'], "message":session['username'] + " viewed your profile"}
			sysmsg(data)
			addprofileviews(result['id'])
		image = profile['path'] if profile != None else 'default.jpeg'
		image_file = url_for('static', filename='photos/' + image)
		try:
			if result['password']:
				del result['password']
			if result['birthdate']:
				data = result['birthdate'].split("-")
				age = get_age(date(int(data[0]), int(data[1]), int(data[2])))
			else:
				age = 0
			return render_template('profile.html', user=result, fame=update_fame_rating(result['id']), profile=image_file, pics=pics, amount=len(pics), blocked=blocked, liked=liked, matched=matched, age=age, tags=tags)
		except TemplateNotFound:
			abort(404)
	else:
		abort(404)

@users.route('/profile/edit', methods=['GET', 'POST'])
@is_logged_in
def edit():
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	if request.method == 'POST':
		cur.execute("SELECT * FROM users WHERE (username=? OR email=?) AND NOT id=?", [request.form.get('username'), request.form.get('email'), session['id']])
		results = cur.fetchall()
		if results:
			flash('Username or email already in use!', 'danger')
			return redirect(url_for('users.edit'))
		else:
			if request.form.get('birthdate'):
				data = request.form.get('birthdate').split("-")
				age = get_age(date(int(data[0]), int(data[1]), int(data[2])))
				if (not age or age < 18):
					flash('You are not allowed to use this site if you are under 18!', 'danger')
					return redirect(url_for('users.edit'))
			else: 
				flash('Please Spesify your Date of birth!', 'danger')
				return redirect(url_for('users.edit'))
			#let user update location removed notif cuz it be useless
			if (not request.form.get('gender')):
				flash('Please Spesify your Gender!', 'danger')
				return redirect(url_for('users.edit'))
				
			if (request.form.get('latCord') and request.form.get('lngCord') and request.form.get('city')):
				cur.execute("UPDATE users SET fname=?, lname=?, username=?, email=?, gender=?, sexuality=?, birthdate=?, bio=?, latCord=?, lngCord=?, city=? WHERE id=?", [request.form.get('fname'), request.form.get('lname'), request.form.get('username'), request.form.get('email'), request.form.get('gender'), request.form.get('sexuality'), request.form.get('birthdate'), request.form.get('bio'), request.form.get('latCord'), request.form.get('lngCord'),request.form.get('city'), session['id']])
				session['latCord'] = request.form.get('latCord')
				session['lngCord'] = request.form.get('lngCord')
				session['city'] = request.form.get('city')
			else:
				cur.execute("UPDATE users SET fname=?, lname=?, username=?, email=?, gender=?, sexuality=?, birthdate=?, bio=? WHERE id=?", [request.form.get('fname'), request.form.get('lname'), request.form.get('username'), request.form.get('email'), request.form.get('gender'), request.form.get('sexuality'), request.form.get('birthdate'), request.form.get('bio'), session['id']])
			con.commit()
			con.close()
			session['username'] = request.form.get('username')
			session['fname'] = request.form.get('fname')
			session['lname'] = request.form.get('lname')
			session['email'] = request.form.get('email')
			try:
				flash('Profile was updated!', 'success')
				return redirect(url_for('users.profile', username=request.form.get('username')))
			except TemplateNotFound:
				abort(404)
	else:
		username = session['username'].lower()
		cur.execute("SELECT * FROM users WHERE username=?", [username])
		result = cur.fetchone()
		con.close()
		if result:
			try:
				return render_template('edit.html', user=result)
			except TemplateNotFound:
				abort(404)
		else:
			abort(404)

@users.route('/profile/tags', methods=['GET', 'POST'])
@is_logged_in
def tags():
	con = db_connect()
	con.row_factory = dict_factory
	cur = con.cursor()
	if request.method == 'POST':
		cur.execute("SELECT * FROM tags WHERE UPPER(tags) = UPPER(?)", [request.form.get('tag')])
		result = cur.fetchall()
		if result:
			flash('Tag already exists!', 'danger')
		else:
			cur.execute("INSERT INTO tags (tags) VALUES (UPPER(?))", [request.form.get('tag')])
			con.commit()
	cur.execute("SELECT * FROM tags WHERE id IN (SELECT tagId FROM usertags GROUP BY tagId ORDER BY COUNT(tagId) DESC LIMIT 5)")
	popular = cur.fetchall()
	cur.execute("SELECT * FROM tags")
	tags = cur.fetchall()
	cur.execute("SELECT * FROM tags WHERE id IN (SELECT tagId FROM usertags WHERE userId=?)", [session['id']])

matcha/users/templates/activity.html
{% extends 'layout.html' %} {% block content %}
<h2 class="text-center">Activity</h2>
<div class="tabs">
	{% if type == 'LIKES' %}
	<a
		href="{{ url_for('users.activity', type='likes') }}"
		class="bg-primary current-tab"
		>Likes</a
	>
	{% else %}
	<a href="{{ url_for('users.activity', type='likes') }}" class="bg-primary"
		>Likes</a
	>
	{% endif %}
	{% if type == 'LIKEDBY' %}
	<a
		href="{{ url_for('users.activity', type='likedBy') }}"
		class="bg-primary current-tab"
		>Liked By</a
	>
	{% else %}
	<a href="{{ url_for('users.activity', type='likedBy') }}" class="bg-primary"
		>Liked By</a
	>
	{% endif %} {% if type == 'MATCHES' %}
	<a
		href="{{ url_for('users.activity', type='matches') }}"
		class="bg-primary current-tab"
		>Matches</a
	>
	{% else %}
	<a href="{{ url_for('users.activity', type='matches') }}" class="bg-primary"
		>Matches</a
	>
	{% endif %} {% if type == 'VIEWS' %}
	<a
		href="{{ url_for('users.activity', type='views') }}"
		class="bg-primary current-tab"
		>Views</a
	>
	{% else %}
	<a href="{{ url_for('users.activity', type='views') }}" class="bg-primary"
		>Views</a
	>
	{% endif %}
	{% if type == 'BLOCKED' %}
	<a
		href="{{ url_for('users.activity', type='blocked') }}"
		class="bg-primary current-tab"
		>Blocked</a
	>
	{% else %}
	<a href="{{ url_for('users.activity', type='blocked') }}" class="bg-primary"
		>Blocked</a
	>
	{% endif %}
</div>
<table class="table table-striped table-hover">
	<thead class="thead-dark">
		<tr >
			{% if type == 'LIKES' %}
			<th scope="col">Like</th scope="col">
			<th scope="col" class="text-right">Unlike</th>
			{% elif type == 'LIKEDBY' %}
			<th scope="col">Liked By</th scope="col">
			{% elif type == 'MATCHES' %}
			<th scope="col">Matched With</th scope="col">
			<th scope="col" class="text-right">Unmatch</th>
			{% elif type == 'VIEWS' %}
			<th scope="col">Viewed By</th scope="col">
			{% elif type == 'BLOCKED' %}
			<th scope="col">Blocked</th scope="col">
			<th scope="col" class="text-right">Unblock</th>
			{% endif %}
		</tr>
	</thead>
	<tbody>
		{% for like in likes %}
		<tr >
			<td>
				<a href="{{ url_for('users.profile', username=like.username) }}"
					>{{ like.username }}</a
				>
			</td>
			{% if type == 'LIKES' %}
			<td>
				<a
					href="{{ url_for('users.like_user', userId=like.id) }}"
					class="text-danger float-right"
					>Unlike</a
				>
			</td>
			{% elif type == 'MATCHES' %}
			<td>
				<a
					href="{{ url_for('users.match_user', userId=like.id) }}"
					class="text-danger float-right"
					>Unmatch</a
				>
			</td>
			{% elif type == 'BLOCKED' %}
			<td>
				<a
					href="{{ url_for('users.block_user', userId=like.id) }}"
					class="text-danger float-right"
					>Unblock</a
				>
			</td>
			{% endif %}
		</tr>
		{% endfor %}
	</tbody>
</table>
{% endblock %}

matcha/users/templates/edit.html
{% extends "layout.html" %} {% block content %}

<div class="content-section">
	<form action="" method="POST">
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Edit Details<a href="{{ url_for('users.profile') }}" class="float-right page-links text-primary">Back</a></legend>
			<div class="form-group">
				<label for="fname" class="form-control-label">First Name</label>
				<input
					type="text"
					name="fname"
					id="fname"
					class="form-control
				form-control-lg"
					value="{{ user.fname }}"
					required
				/>
			</div>
			<div class="form-group">
				<label for="lname" class="form-control-label">Last Name</label>
				<input
					type="text"
					name="lname"
					id="lname"
					class="form-control form-control-lg"
					value="{{ user.lname }}"
					required
				/>
			</div>
			<div class="form-group">
				<label for="username" class="form-control-label"
					>Username</label
				>
				<input
					type="text"
					name="username"
					id="username"
					class="form-control form-control-lg"
					value="{{ user.username }}"
					required
				/>
			</div>
			<div class="form-group">
				<label for="email" class="form-control-label">Email</label>
				<input
					type="text"
					name="email"
					id="email"
					class="form-control form-control-lg"
					value="{{ user.email }}"
					required
				/>
			</div>
			<div class="form-row align-items-center">
				<div class="col-auto my-1">
					<label class="mr-sm-2" for="gender">Gender</label>
					<select
						class="custom-select mr-sm-2 form-control form-control-lg"
						id="gender"
						name="gender"
					>
						{% if user.gender %} {% if user.gender == 'M' %}
						<option selected hidden value="M">Male</option>
						{% elif user.gender == 'F' %}
						<option selected hidden value="F">Female</option>
						{% else %}
						<option selected hidden value="O">Other</option>
						{% endif %} {% else %}
						<option disabled selected hidden>Choose...</option>
						{% endif %}
						<option value="M">Male</option>
						<option value="F">Female</option>
						<option value="O">Other</option>
					</select>
				</div>
				<div class="col-auto my-1">
					<label class="mr-sm-2" for="gender">Sexuality</label>
					<select
						class="custom-select mr-sm-2 form-control form-control-lg"
						id="sexuality"
						name="sexuality"
					>
						{% if user.sexuality %} {% if user.sexuality == 'S' %}
						<option selected hidden value="S">Heterosexual</option>
						{% elif user.sexuality == 'G' %}
						<option selected hidden value="G">Homosexual</option>
						{% else %}
						<option selected hidden value="B">Bisexual</option>
						{% endif %}{% else %}
						<option disabled selected hidden>Choose...</option>
						{% endif %}
						<option value="S">Heterosexual</option>
						<option value="G">Homosexual</option>
						<option value="B">Bisexual</option>
					</select>
				</div>
			</div>
			<div class="form-group">
				<label for="birthdate" class="form-control-label"
					>Birthdate</label
				>
				<input
					type="date"
					name="birthdate"
					id="birthdate"
					max="9999-12-12"
					class="form-control form-control-lg"
					value="{{ user.birthdate }}"
					required
				/>
			</div>
			<div class="form-group">
				<label for="bio">Bio</label>
				<textarea
					class="form-control rounded-0"
					id="bio"
					name="bio"
					rows="3"
					maxlength="255"
				>
{{ user.bio }}</textarea
				>
			</div>

			<div class="form-group">
				<label for="btnloc" class="form-control-label">Location:</label>
				<div class="form-group">
					<a
						name="btnloc"
						id="btnloc"
						onclick="getlocation()"
						class="btn btn-outline-primary"
						>Detect Location</a
					><br />
				</div>
				<!-- PLACE HOLDERS -->
			<div class="form-group">
				{% if user.latCord %}
					<input type="hidden" name="latCord" value="{{ user.latCord }}"/>
				{% endif %}
			</div>
			<div class="form-group">
				{% if user.lngCord %}
					<input type="hidden" name="lngCord" value="{{ user.lngCord }}" />
				{% endif %}
			</div>

				<div class="form-group">
					<label for="city" class="form-control-label">City</label>
					{% if user.city %}
					<input
						type="text"
						name="city"
						id="city"
						placeholder="city"
						class="form-control rounded-0"
						value="{{ user.city }}"
						required
					/>
					{% else %}
					<input
						type="text"
						name="city"
						id="city"
						placeholder="city"
						class="form-control rounded-0"
						required
					/>
					{% endif %}
				</div>
			</div>
			<!-- Notifications toggle button -->
			<a onclick="setpermission()" class="btn btn-outline-primary"
				>Enable Notifications</a
			>
		</fieldset>
		<div class="form-group d-flex justify-content-between">
			<button type="submit" class="btn btn-outline-primary">
				Edit
			</button>
			<small class="align-self-center"
				><a href="{{ url_for('users.password') }}" class="text-primary"
					>Change Password</a
				></small
			>
		</div>
	</form>
</div>

{% endblock content %}

matcha/users/templates/password.html
{% extends "layout.html" %} {% block content %}

<div class="content-section">
	<form action="" method="POST">
		<fieldset class="form-group">
			<legend class="border-bottom mb-4">Change Password</legend>
			<div class="form-group">
				<label for="password" class="form-control-label"
					>New Password</label
				>
				<input
					type="password"
					name="password"
					id="password"
					class="form-control form-control-lg"
					required
				/>
			</div>
			<div class="form-group">
				<label for="confirm" class="form-control-label"
					>Confirm Password</label
				>
				<input
					type="password"
					name="confirm"
					id="confirm"
					class="form-control form-control-lg"
					required
				/>
			</div>
		</fieldset>
		<div class="form-group d-flex justify-content-between">
			<button type="submit" class="btn btn-outline-primary">
				Change
			</button>
			<small class="align-self-center"
				><a href="{{ url_for('users.edit') }}" class="text-primary"
					>Edit Profile</a
				></small
			>
		</div>
	</form>
</div>

{% endblock content %}

matcha/users/templates/profile.html
{% extends 'layout.html' %} {% block content %}

<div class="content-section">
	<div class="row">
		<div class="media col-md-8">
			<img class="rounded-circle account-img" src="{{ profile }}" />
			<div class="media-body">
				<h2 class="account-heading">{{ user.username }}</h2>
				<h4>{{ user.fname }} {{ user.lname }}</h4>
				{% if user.bio %}
				<span style="word-break: break-word;">{{ user.bio }}</span>
				{% else %}
				<span style="word-break: break-word;">No bio given</span>
				{% endif %}
			</div>
		</div>
	</div>
	<br>
	<div>
		{% if not user.username or session.username == user.username.lower() %}
		<legend class="border-bottom mb-4">Info<a href="{{ url_for('users.edit') }}" class="float-right page-links text-primary">Edit</a></legend>
		{% else %}
		<legend class="border-bottom mb-4">Info</legend>
		{% endif %}
		<div>
			<p class="info-heads"><b>Age:</b></p>
			{% if age > 0 %}
			<span style="word-break: break-word;">{{ age }} Years old</span>
			{% else %}
			<span style="word-break: break-word;">No age specified</span>
			{% endif %}
		</div>
		<br>
		<div>
			<p class="info-heads"><b>Gender:</b></p>
			{% if not user.gender %}
			<span style="word-break: break-word;">No gender provided</span>
			{% else %}
				{% if user.gender == 'M' %}
				<span style="word-break: break-word;">Male</span>
				{% elif user.gender == 'F' %}
				<span style="word-break: break-word;">Female</span>
				{% else %}
				<span style="word-break: break-word;">Other</span>
				{% endif %}
			{% endif %}
		</div>
		<br>
		<div>
			<p class="info-heads"><b>Sexuality:</b></p>
			{% if not user.sexuality %}
			<span style="word-break: break-word;">No sexuality provided</span>
			{% else %}
				{% if user.sexuality == 'S' %}
				<span style="word-break: break-word;">Heterosexual</span>
				{% elif user.sexuality == 'G' %}
				<span style="word-break: break-word;">Homosexual</span>
				{% else %}
				<span style="word-break: break-word;">Bisexual</span>
				{% endif %}
			{% endif %}
		</div>
		<br>
	</div>
	<div>
		{% if not user.username or session.username == user.username.lower() %}
		<legend class="border-bottom mb-4">Tags<a href="{{ url_for('users.tags') }}" class="float-right page-links text-primary">Edit</a></legend>
		{% else %}
		<legend class="border-bottom mb-4">Tags</legend>
		{% endif %}
		{% if tags %}
			<span style="word-break: break-word;">
			{% for tag in tags %}
			#{{ tag.tags }}&nbsp;&nbsp;&nbsp;
			{% endfor %}
			</span>
		{% else %}
			<span>No tags chosen</span>
		{% endif %}
	</div>
</div>

<div class="content-section">
	<legend class="border-bottom mb-4">Photos</legend>
	<div class="row text-center">
		{% for pic in pics %}
		<figure class="col-md-4">
			<img
				alt="picture"
				src="{{url_for('static', filename='photos/' + pic.path)}}"
				class="user-pics"
			/>
			{% if not user.username or session.username == user.username.lower() %}
			<a href="{{ url_for('users.set_pic', photoId=pic.id) }}" class="btn btn-primary">Set AVI</a>
			<a href="{{ url_for('users.delete_pic', photoId=pic.id) }}" class="btn btn-danger">Delete</a>
			{% endif %}
		</figure>
		{% endfor %}
	</div>
	<div class="row text-center">
		{% if amount < 5 and (not user.username or session.username == user.username.lower()) %}
		<form id="PhotoForm" action="" method="POST" enctype="multipart/form-data" class="col-md-4 addMoreButton">
				<input type="file" name="picture" id="picture">
		</form>
		<script>
			// Auto upload
			function chooseFile() {
			$("#fileInput").click();
				}
				var picture = document.getElementById('picture')
				picture.addEventListener('change',() => {
						var myForm = document.getElementById("PhotoForm")
						myForm.submit();
				});
		</script>
		{% endif %}
	</div>
</div>

{% endblock %}

{% block sidebar %}

<div class="content-section text-center">
	<div class="fameRating">
		<h4>{{ fame }} / 5</h4>
		<h4>Fame Rating</h4>
	</div>
	{% if not user.username or session.username == user.username.lower() %}
	<p>
		<ul class="list-group">
			<li class="list-group-item list-group-item-light"><a href="{{ url_for('users.activity', type='likes') }}" class="text-primary">Activity</a></li>
			<li class="list-group-item list-group-item-light"><a href="{{ url_for('users.tags') }}" class="text-primary">Edit Tags</a></li>
			<li class="list-group-item list-group-item-light"><a href="{{ url_for('users.edit') }}" class="text-primary">Edit Profile</a></li>
			<li class="list-group-item list-group-item-light"><a href="{{ url_for('users.password') }}" class="text-primary">Change Password</a></li>
		</ul>
	</p>
	{% else %}
	<hr>
		{% if user.lastonline == "now" %}
		<span>Online now</span>
		<br>
		{% elif user.lastonline %}
		<span>Last online: {{ user.lastonline }}</span>
		<br>
		{% else %}
		<span>Offline</span>
		<br>
		{% endif %}

	{% if user.id != 1 %}
		{% if matched == 1%}
		<a class="btn btn-primary" name= "submit" href="{{ url_for('users.match_user', userId=user.id) }}" role="button">Unmatch</a>
		{% else %}
			{% if liked == 1%}
			<a class="btn btn-primary" name= "submit" href="{{ url_for('users.like_user', userId=user.id) }}" role="button">Unlike</a>
			{% else %}
			<a class="btn btn-primary" name= "submit" href="{{ url_for('users.like_user', userId=user.id) }}" role="button">Like</a>
			{% endif %}
		{% endif %}
		{% if blocked == 1 %}
		<a class="btn btn-danger" name= "submit" href="{{ url_for('users.block_user', userId=user.id) }}" role="button">Unblock</a>
		{% else %}
		<a class="btn btn-danger" name= "submit" href="{{ url_for('users.block_user', userId=user.id) }}" role="button">Block</a>
		{% endif %}
		<a class="btn btn-danger" href="{{ url_for('users.report_user', userId=user.id) }}" role="button">Report</a>
	{% endif %}
	</form>
	{% endif %}
</div>

{% endblock %}

matcha/users/templates/tags.html
{% extends "layout.html" %} {% block content %}

<div class="content-section">
	<h1>Tags<a href="{{ url_for('users.profile') }}" class="float-right page-links text-primary">Back</a></h1>
	<div>
		<legend class="border-bottom mb-4">Popular Tags</legend>
		{% for pop in popular %}
		<a
			class="btn btn-tags"
			href="{{ url_for('users.pick_tag', tagId=pop.id) }}"
			>{{ pop.tags }}</a
		>
		{% endfor %}
	</div>
	<br />
	<div>
		<legend class="border-bottom mb-4">All Tags</legend>
		{% for tag in tags %}
		<a
			class="btn btn-tags"
			href="{{ url_for('users.pick_tag', tagId=tag.id) }}"
			>{{ tag.tags }}</a
		>
		{% endfor %}
	</div>
	<br />
	<div>
		<legend class="border-bottom mb-4">My Tags</legend>
		{% for my in mine %}
		<a
			class="btn btn-tags"
			href="{{ url_for('users.pick_tag', tagId=my.id) }}"
			>{{ my.tags }}</a
		>
		{% endfor %}
	</div>
	<br />
	<div>
		<form action="" method="POST">
			<fieldset class="form-group">
				<legend class="border-bottom mb-4">Add Tag</legend>
				<div class="form-group">
					<label for="tag" class="form-control-label">New Tag</label>
					<input
						type="text"
						name="tag"
						id="tag"
						class="form-control form-control-lg"
					/>
				</div>
			</fieldset>
			<div class="form-group d-flex justify-content-between">
				<button type="submit" class="btn btn-outline-primary">
					Add
				</button>
			</div>
		</form>
	</div>
</div>

{% endblock content %}